### ISSUE TITLE
Addendum for install.md

### ISSUE THREAD

**Issue by ojaksch** [MiSTerArch/PKGBUILDs#7]
Just successfully finished my install of MiSTerArch...went straight forward. Feels like "at home" :)
But two suggestions for install.md, where a newbe may stumble on:
* When the user login as 'alarm', he has to do the next steps as root ("su -"), but install.md is missing the hint for root's password, what is 'root' here
* The tasks where 'pacman' comes into play may need the population of Arch's PGP keyring for signed packages beginning with pacman v6:
```
pacman-key --init && pacman-key --populate archlinuxarm
```
Otherwise there is nothing else to report so far. Looking forward to this!

**Comment by amstan** [comment]
Thank you, I always appreciate someone offering feedback on such instructions with fresh eyes. Stay tuned for a fix.

**Comment by ojaksch** [comment]
Always on service! :)
I assume that you've created your own repo, because it's documented and working - I'd go and close #6 then...
```
[misterarch]
SigLevel = Optional TrustedOnly
Server = http://misterarch.hypertriangle.com/repo
```
