### ISSUE TITLE
Enable f2fs in kernel config

### ISSUE THREAD

**Issue by solskogen** [MiSTerArch/PKGBUILDs#8]

**Comment by amstan** [comment]
I'm guessing we're talking about just `CONFIG_F2FS_FS`? See https://github.com/torvalds/linux/blob/master/fs/f2fs/Kconfig for the options available.

Would you be willing to learn how to do this? It's fairly straight forward (though the eventual compiling might take a while). That way you can help with future kernel configuration (via pull requests). If not I guess I can do it myself when I get to it soon.

**Comment by solskogen** [comment]
I'll do that in the future :-)

**Comment by amstan** [comment]
```
alex@MiSTer:~% sudo pacman -Syu; sudo reboot
....
Packages (2) linux-mister-5.15-5  linux-mister-headers-5.15-5
....
alex@MiSTer:~% uname -a
Linux MiSTer 5.15.1-5 #1 SMP Sat Mar 5 14:18:30 PST 2022 armv7l GNU/Linux
alex@MiSTer:~% zcat /proc/config.gz|grep F2FS
CONFIG_F2FS_FS=y
....
alex@MiSTer:~% sudo mount -t randomunknownfs /dev/zero /mnt
mount: /mnt: unknown filesystem type 'randomunknownfs'.
alex@MiSTer:~% sudo mount -t f2fs /dev/zero /mnt
mount: /mnt: /dev/zero is not a block device.
# I don't really have one to test with :D, so here's it with /dev/zero
